### ISSUE TITLE
Sources are missing

### ISSUE THREAD

**Issue by bttrx** [axtens/in#1]
Only LICENSE and README.md are available in the repo.

**Comment by axtens** [comment]
Wow, someone's actually digging around in my old code. Umm ... right I'd better do something about that.

**Comment by axtens** [comment]
Okay. Done. Thanks.

**Comment by bttrx** [comment]
I was another MoonRock user 20 years ago.

**Comment by axtens** [comment]
My goodness, Moonrock! I wonder what happened to the author? As for IN.MOD,
that's Fitted Software Tools Modula-2.

**Comment by bttrx** [comment]
I was in contact with Rowan around December 2020 asking to release MoonRock sources under a libre license. He liked the idea in general, but it still didn't happen. Probably due too much real life.

I have no experience with Modula. Sure, it's the successor of Pascal, but it seems to have so much "red tape", similar to Microsoft MASM syntax.

**Comment by axtens** [comment]
Yes, M2 has lots of red tape. A bit like C# with its "public partial static class" and the like. The M2 code compiles under FST M2. Oh, and case-sensitive too.

**Comment by axtens** [comment]
Have added the binary
